"""
Generate a synthetic AG News sample CSV for training when the real dataset is unavailable.
Creates 200 rows (50 per class) with realistic news article text.
Run this once: python app/create_ag_news_sample.py
"""

import os
import pandas as pd

SAMPLES_DIR = "data/samples"

POLITICS = [
    "The United Nations Security Council held an emergency session on rising tensions in the Middle East region.",
    "President signs new climate agreement with world leaders at international summit in Geneva.",
    "Congress passes bipartisan infrastructure bill worth 1.2 trillion dollars amid heated debate.",
    "Foreign ministers meet in Brussels to discuss NATO expansion and security cooperation.",
    "Opposition party calls for snap elections after prime minister faces corruption allegations.",
    "Senate committee approves new sanctions against rogue states over human rights violations.",
    "White House announces diplomatic mission to ease relations with neighboring country.",
    "Government unveils sweeping immigration reform plan affecting millions of residents.",
    "European parliament votes on new data privacy regulation affecting tech companies.",
    "Peace talks between two rival nations resume after months of failed negotiations.",
    "Defense secretary briefs lawmakers on military deployments in contested region.",
    "State department issues travel advisory for citizens amid escalating civil unrest.",
    "G7 leaders agree on global minimum corporate tax rate framework.",
    "National security council warns of growing cyber threats from foreign actors.",
    "Prime minister survives no-confidence vote in tense parliamentary session.",
    "Presidential candidate unveils healthcare reform platform ahead of primary.",
    "UN peacekeeping mission extended for another year in troubled African nation.",
    "Trade war threatens to escalate as tariffs are imposed on imported goods.",
    "Governor declares state of emergency after devastating natural disaster hits coast.",
    "International court issues ruling on territorial dispute between two nations.",
    "Lawmakers debate controversial surveillance bill in closed-door session.",
    "Foreign aid package approved to support rebuilding efforts in war-torn country.",
    "President meets with top generals to review national defense strategy.",
    "New electoral reform law passes amid protests from opposition groups.",
    "Diplomatic tensions rise as ambassadors are recalled from respective capitals.",
    "Budget committee debates spending cuts to reduce national debt level.",
    "Secretary of state embarks on multi-nation tour to strengthen alliances.",
    "Whistleblower reveals classified documents related to intelligence operations.",
    "Census data reshapes electoral map ahead of upcoming midterm elections.",
    "Parliament approves controversial anti-terrorism legislation after long debate.",
    "President announces withdrawal of troops from overseas military base.",
    "Coalition government collapses as junior partner withdraws support.",
    "UN report warns of humanitarian crisis in conflict-affected region.",
    "New foreign policy doctrine shifts focus from military to diplomacy.",
    "Local elections signal shift in voter sentiment ahead of national polls.",
    "Governor signs criminal justice reform bill into law.",
    "Refugee crisis prompts emergency meeting of European interior ministers.",
    "Congress holds hearing on foreign interference in democratic elections.",
    "International sanctions imposed on regime after disputed election results.",
    "President nominates new supreme court justice to fill vacant seat.",
    "Ministry of finance announces austerity measures to stabilize economy.",
    "Bilateral trade agreement signed after three years of negotiations.",
    "Former president indicted on corruption charges by special prosecutor.",
    "Health minister resigns amid scandal over pandemic contract awards.",
    "Rebel forces capture key city as government troops retreat.",
    "Parliament debates proposed changes to constitution amid protests.",
    "Security forces crack down on demonstrators in capital city.",
    "Prime minister pledges to tackle housing crisis with new legislation.",
    "International observers criticize election process as flawed and unfair.",
    "Government minister faces calls to resign over leaked private messages.",
]

SPORTS = [
    "Manchester United defeats Real Madrid in thrilling Champions League semifinal.",
    "LeBron James scores 40 points to lead Lakers past Golden State Warriors.",
    "Tiger Woods announces comeback after recovering from back surgery.",
    "Serena Williams wins her 24th Grand Slam title at Wimbledon tournament.",
    "New York Yankees clinch American League pennant with dramatic comeback win.",
    "Olympic committee announces new sports added to 2028 Los Angeles games.",
    "Football superstar signs record-breaking contract worth 250 million dollars.",
    "NBA draft sees record number of international players selected in first round.",
    "Tour de France leader crashes out of race on treacherous mountain stage.",
    "National team coach resigns after shock defeat in World Cup qualifier.",
    "New stadium construction approved for NFL franchise relocation to new city.",
    "Boxing champion retains title after controversial split decision victory.",
    "Swimming world record broken at international championship in Budapest.",
    "College basketball tournament upsets shock fans as top seeds eliminated.",
    "Tennis star banned from competition after positive doping test result.",
    "Formula 1 champion secures fourth consecutive world drivers title.",
    "Golf major championship comes down to thrilling playoff on final hole.",
    "Basketball player traded to contending team just before deadline.",
    "Soccer club announces signing of teenage sensation from South American league.",
    "Marathon runner sets new course record in wet and windy conditions.",
    "Rugby world cup hosts defeat defending champions in opening match.",
    "Baseball player hits 60th home run of season chasing all-time record.",
    "Olympic sprinter wins 100 meter final in world record time.",
    "Soccer referee suspended after controversial decisions in cup final.",
    "League introduces new rules to improve game flow and reduce stoppages.",
    "Star quarterback announces retirement after 15 season career in NFL.",
    "Ice hockey team wins Stanley Cup in epic seven-game final series.",
    "Athletics federation bans country from international competition.",
    "Young tennis prodigy wins first grand slam at just seventeen years old.",
    "Cricket team wins test series in dominant performance on foreign soil.",
    "Sports governing body launches investigation into match-fixing allegations.",
    "Coach of the year award goes to surprise candidate from small market team.",
    "World chess champion defends title in tense tiebreak game.",
    "Cycling team disqualified from race after banned substance found.",
    "New transfer record set as striker joins rival club for huge fee.",
    "NBA franchise granted expansion rights in new market city.",
    "Decathlon world champion breaks four individual world records.",
    "Sports arbitration tribunal rules in favor of suspended athlete.",
    "Season ticket sales break records as team announces new arena plans.",
    "Football manager signs five year contract extension after title win.",
    "Paralympic champion inspires next generation with record-breaking performance.",
    "Sports committee recommends stricter regulations on youth training programs.",
    "Home side wins hosting rights for next edition of continental championship.",
    "Veteran player makes emotional return after year-long injury absence.",
    "Basketball league expands to two new international cities next season.",
    "Track star tests positive and stripped of three medals from past games.",
    "Goalkeeper breaks clean sheet record in longest shutout streak in history.",
    "Women's soccer league attendance reaches all-time high this season.",
    "Sports media rights deal worth billions reshapes broadcast landscape.",
    "Young golfer becomes youngest player to win Masters tournament title.",
]

BUSINESS = [
    "Apple reports record quarterly profits driven by strong iPhone 15 sales.",
    "Federal Reserve raises interest rates by 25 basis points to combat inflation.",
    "Amazon announces plans to hire 50000 workers for holiday shopping season.",
    "Stock market closes at all-time high as tech sector leads gains.",
    "Tesla faces production challenges as supply chain disruptions continue.",
    "Oil prices surge amid geopolitical tensions in major producing regions.",
    "Bank of America warns of potential recession risk in next 12 months.",
    "Google parent Alphabet posts disappointing quarterly advertising revenue.",
    "Major airline announces bankruptcy protection amid mounting debt burden.",
    "Cryptocurrency market cap falls below one trillion dollars as prices crash.",
    "Retail sales data shows stronger than expected consumer spending growth.",
    "Merger deal between two pharmaceutical giants valued at 80 billion dollars.",
    "Chinese exports fall sharply as global demand weakens across sectors.",
    "Goldman Sachs lays off thousands of employees amid revenue decline.",
    "New York Stock Exchange introduces trading curbs to limit volatility.",
    "Warren Buffett increases stake in energy companies amid market volatility.",
    "IMF revises global growth forecast downward citing multiple risk factors.",
    "Startup unicorn raises 500 million dollar funding round at 10 billion valuation.",
    "Manufacturing index contracts for third consecutive month signaling slowdown.",
    "Elon Musk sells Tesla shares worth 4 billion dollars in single transaction.",
    "US inflation falls for sixth straight month as Fed policy takes effect.",
    "European central bank holds rates steady amid slowing economic growth.",
    "Walmart beats earnings estimates as budget-conscious shoppers increase visits.",
    "Real estate market cools as mortgage rates hit decade-long high.",
    "Semiconductor shortage eases as new chip fabrication plants come online.",
    "Credit card delinquency rates rise to highest level since financial crisis.",
    "Luxury goods maker reports record sales as wealthy consumers keep spending.",
    "Venture capital funding drops 40 percent compared to previous year.",
    "Insurance company raises premiums citing increased frequency of weather events.",
    "Bond yields invert as investors seek safety amid economic uncertainty.",
    "Pharmaceutical company wins approval for breakthrough cancer treatment drug.",
    "Retail giant closes 150 stores as online shopping continues to grow.",
    "Trade deficit narrows as exports surge and imports fall sharply.",
    "Commercial real estate faces crisis as office vacancy rates hit new highs.",
    "Central bank governor signals possible end to rate hiking cycle.",
    "Automaker announces 5 billion dollar investment in electric vehicle production.",
    "Grocery prices stabilize after two years of above-average food inflation.",
    "Bank stress test results show major institutions remain well capitalized.",
    "Supply chain resilience improves as companies diversify sourcing strategies.",
    "Private equity firm acquires struggling retail chain for 2 billion dollars.",
    "Housing starts fall as builders face high costs and low buyer demand.",
    "Consumer confidence index drops to lowest level in six months.",
    "Airline profits soar as travel demand remains robust despite higher fares.",
    "Small business optimism index falls amid concerns about future conditions.",
    "Energy company reports record profits driven by elevated commodity prices.",
    "Unemployment rate holds steady as labor market shows continued resilience.",
    "Tech layoffs continue as companies cut costs and restructure operations.",
    "Currency intervention fails to stop decline of emerging market currencies.",
    "Luxury automaker faces recall of 200000 vehicles over safety defect.",
    "Earnings season kicks off with mixed results across major sectors.",
]

TECHNOLOGY = [
    "OpenAI releases GPT-5 with unprecedented reasoning capabilities and benchmark scores.",
    "NASA scientists confirm discovery of water ice in permanently shadowed lunar crater.",
    "New quantum computing breakthrough achieves 1000 qubit entanglement milestone.",
    "SpaceX successfully launches 60 Starlink satellites into low earth orbit.",
    "Scientists develop biodegradable plastic substitute from seaweed extract.",
    "CRISPR gene editing trial shows promising results for sickle cell disease.",
    "Meta unveils new virtual reality headset with improved resolution and battery.",
    "Researchers demonstrate room-temperature superconductor material breakthrough.",
    "Electric vehicle battery with 500-mile range enters mass production phase.",
    "Cybersecurity firm discovers major zero-day vulnerability in popular software.",
    "Brain-computer interface enables paralyzed patient to control robotic arm.",
    "New solar panel efficiency record achieved by university research team.",
    "Fusion energy reactor sustains plasma for record 17 seconds at high temperature.",
    "Autonomous vehicle company expands robotaxi service to three new cities.",
    "Researchers create artificial protein that fights antibiotic-resistant bacteria.",
    "Satellite internet service achieves gigabit speeds for remote rural areas.",
    "Tech giant fined 1.2 billion dollars for antitrust violations in Europe.",
    "New chip architecture delivers 10x performance improvement at lower power.",
    "Scientists sequence genome of previously unknown deep-sea creature species.",
    "AI model outperforms human doctors at diagnosing rare genetic conditions.",
    "Drone delivery service receives approval to operate in urban airspace.",
    "Climate model predicts higher global temperature rise than previous estimates.",
    "Smart contact lens that monitors glucose levels approved for commercial use.",
    "Researchers develop algorithm that predicts protein folding with high accuracy.",
    "Space telescope captures deepest infrared image of early universe ever taken.",
    "New material converts heat directly into electricity with record efficiency.",
    "Robotics company unveils humanoid robot capable of complex manufacturing tasks.",
    "Internet infrastructure under strain as traffic reaches new global record.",
    "Scientists develop vaccine platform that can be rapidly adapted for new viruses.",
    "5G network expansion reaches rural communities previously without broadband.",
    "Social media algorithm audit reveals hidden bias in content recommendations.",
    "New programming language claims to eliminate entire class of security bugs.",
    "Exoplanet atmosphere reveals presence of water vapor and carbon dioxide.",
    "Wearable device predicts seizures up to 30 minutes before they occur.",
    "Researchers use AI to discover three new antibiotic compounds from soil.",
    "Microplastics found in human brain tissue for first time in autopsy study.",
    "Wireless charging standard reaches 100 watt power delivery milestone.",
    "Scientists grow functional mini-organs from stem cells for drug testing.",
    "Deepfake detection tool achieves 97 percent accuracy in independent test.",
    "New encryption standard adopted by government agencies to resist quantum attacks.",
    "Satellite data reveals accelerating ice loss in Antarctica at record rate.",
    "Autonomous weapons treaty negotiations stall as major powers disagree.",
    "AI system generates novel drug candidate that passes initial safety tests.",
    "Researchers train model that translates brain signals into speech.",
    "New data center design cuts energy consumption by 40 percent using liquid cooling.",
    "Space agency announces mission to retrieve sample from asteroid belt object.",
    "Tech company releases open-source large language model to research community.",
    "Scientists demonstrate quantum teleportation over 100 kilometer fiber link.",
    "Digital twin technology reduces aircraft maintenance costs by 30 percent.",
    "New battery chemistry eliminates fire risk while doubling energy density.",
]

def generate_ag_news_sample():
    """Build a 200-row AG News sample (50 per class) and save to data/samples/."""
    rows = []
    categories = [
        (POLITICS,    0, 'Politics'),
        (SPORTS,      1, 'Sports'),
        (BUSINESS,    2, 'Business'),
        (TECHNOLOGY,  3, 'Technology'),
    ]

    for texts, label_int, label_name in categories:
        for text in texts[:50]:
            rows.append({'text': text, 'label': label_int, 'label_name': label_name})

    df = pd.DataFrame(rows)
    df = df.sample(frac=1, random_state=42).reset_index(drop=True)   # shuffle

    os.makedirs(SAMPLES_DIR, exist_ok=True)
    out_path = os.path.join(SAMPLES_DIR, 'ag_news_sample.csv')
    df.to_csv(out_path, index=False)

    print(f"AG News sample created: {out_path}  ({len(df)} rows)")
    print("\nClass distribution:")
    print(df['label_name'].value_counts())

if __name__ == "__main__":
    generate_ag_news_sample()
